org: chrismlittle
app: project-template
service: project-template

variablesResolutionMode: 20210326

package:
  individually: true
  exclude:
    - "*/**"

provider:
  name: aws
  runtime: python3.9
  stage: dev
  region: eu-west-2
  timeout: 30
  memorySize: 1024
  lambdaHashingVersion: 20201221
  deploymentPrefix: serverless-lambdas


custom:
  pythonRequirements:
    usePoetry: false
    zip: true

plugins:
  - serverless-python-requirements